version: '3'

services:
  hugo_app:
    container_name: hugo_app
    build:
      context: .
      dockerfile: hugo.dockerfile
    ports:
      - 1313:1313
    tty: true
    volumes:
      - ./hugo:/hugo
