[build]
publish = "./hugo/public"
command = "hugo -s ./hugo"

[context.production.environment]
HUGO_VERSION = "0.58.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
HUGO_VERSION = "0.58.3"

[context.branch-deploy.environment]
HUGO_VERSION = "0.58.3"
